### PR TITLE
fix: use globbySync to resolve PNPM global node_modules paths

### LINKED ISSUE #693: yo unable to find generators installed with pnpm
I was trying to use yo and generator-office installed via pnpm.
This line below resolves to the ```global/*/node_modules``` which is not an actual directory.
https://github.com/yeoman/environment/blob/9c3ae835c79cc9e7814a5f72d50ab8bafef32c1c/src/module-lookup.ts#L273-L275
When attempting to find modules in ```global/*/node_modules``` this ```existsSync(root)``` fails.
https://github.com/yeoman/environment/blob/9c3ae835c79cc9e7814a5f72d50ab8bafef32c1c/src/module-lookup.ts#L110-L118

The result when using yo is this with generator-office installed globally with pnpm is this.
```bash
Error office

You don't seem to have a generator with the name “generator-office” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-office.

To see all your installed generators run yo --generators. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
```

pr to fix here #692

### PR DESCRIPTION
**Pull request by phishbacon**
Fixes #693 

## Purpose of this pull request? 

- [ ] Documentation update
- [X] Bug fix 
- [ ] Enhancement
- [ ] Other, please explain:

## What changes did you make?

Switched to using globbySync when pushing all pnpm node_module directories to paths array. The ```global/*/node_modules``` path was failing this existsSync check as the directory doesn't actually exist and so none of the pnpm installed generators could be found
```js
if (!existsSync(root) || (!lstatSync(root).isDirectory() && !lstatSync(root).isSymbolicLink())) {
      continue;
```

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Looks good to me, thanks for hopping onto a fix! I confirmed locally that e.g. `/Users/josh/Library/pnpm/global/5/node_modules` does include the generator after `pnpm i -g generator-office`.

This area is finnicky and new, so we should definitely hear from >=1 of @mshima and @UlisesGascon for review.

File: src/module-lookup.ts [hunk 1]
```diff
@@ -271,7 +271,15 @@ function getGlobalNpmPaths(filterPaths = true): string[] {
...
   if (process.env.PNPM_HOME) {
-    paths.push(resolve(process.env.PNPM_HOME, 'global/*/node_modules'));
+    const pnpmHome = process.env.PNPM_HOME;
+    paths.push(
+      ...globbySync('global/*/node_modules', {
+        cwd: pnpmHome,
+        onlyDirectories: true,
+        suppressErrors: true,
+        absolute: true,
+      }).map(modulesPath => resolve(pnpmHome, modulesPath)),
```
Comment (mshima) [inline src/module-lookup.ts]: Since we are requesting absolute paths, pnpmHome in resolve should not be required.
```suggestion
      }).map(modulesPath => resolve(modulesPath)),
```
