### PR TITLE
Fix namespace resolution for paths with more than one '.js' in it

### LINKED ISSUE #30: Finding global generators on io.js
For some reason global generator cannot be found on io.js - this also cause a test failure on Travis when using io.js.

Note: I have **not** reproduce this myself of a system, I need to investigate and reproduce. We know we have a test failure. That doesn't mean it is not working.

### PR DESCRIPTION
**Pull request by whitlockjc**
* This bug is not an io.js issue but really an issue with any module
  path that has more than one '.js' in its path.  Since io.js is
  typically installed into a directory called 'io.js', if you have a
  generator path of
  /path/to/io.js/node_modules/lib/generators/yo/index.js, the first
  occurance of '.js' was replaced instread of the '.js' in 'index.js'.

Fixes #30

### CODE REVIEW

**Comment by SBoudrias** [comment]
Ah great!! Thanks for digging this one up!

File: lib/environment.js [hunk 1]
```diff
@@ -357,7 +357,7 @@ Environment.prototype.namespace = function namespace(filepath) {
   }
 
   // cleanup extension and normalize path for differents OS
-  var ns = path.normalize(filepath.replace(path.extname(filepath), ''));
+  var ns = path.normalize(filepath.replace(new RegExp(path.extname(filepath) + '$'), ''));
```
Comment (sindresorhus) [inline lib/environment.js]: The string needs to be escaped before it's used in a regex => https://github.com/sindresorhus/escape-string-regexp

**Comment by whitlockjc** [comment]
I thought about that lying in bed last night.  It occurred to me the `.` in the extension name would match any character.  I'll submit a fix if it's not already done when I get to the keyboard.

File: lib/environment.js (hunk 1 above)
Comment (whitlockjc) [inline lib/environment.js]: PR #32 should fix this.
